# Generated by Django 6.0.6 on 2026-07-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_assessmentframework_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Prompt', max_length=255)),
                ('prompt', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='documents.assessmentframework')),
            ],
            options={
                'ordering': ['framework', '-version'],
            },
        ),
    ]
