# Generated by Django 6.0.6 on 2026-07-02 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_frameworkprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('ai_description', models.TextField(blank=True)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.assessmentframework')),
            ],
            options={
                'ordering': ['framework', 'display_order'],
            },
        ),
    ]
