# Generated by Django 6.0.6 on 2026-07-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_frameworkfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('startswith', 'Starts With'), ('endswith', 'Ends With')], default='contains', max_length=20)),
                ('match_value', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('eligible', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='documents.assessmentframework')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
