# Generated by Django 6.0.6 on 2026-07-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_frameworkrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkrule',
            name='rule_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='frameworkrule',
            name='rule_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frameworkrule',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='frameworkrule',
            name='match_value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='frameworkrule',
            name='operator',
            field=models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('startswith', 'Starts With'), ('endswith', 'Ends With'), ('regex', 'Regex')], default='contains', max_length=20),
        ),
    ]
