# Generated by Django 6.0.6 on 2026-07-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_frameworkrule_rule_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('min_days', models.PositiveIntegerField(default=1)),
                ('max_days', models.PositiveIntegerField(default=365)),
                ('weightage_per_day', models.FloatField()),
                ('max_score', models.FloatField(default=9999)),
                ('remarks', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='documents.assessmentframework')),
            ],
            options={
                'ordering': ['framework', 'priority'],
            },
        ),
    ]
