# Generated by Django 6.0.6 on 2026-07-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_scoringrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('column_title', models.CharField(max_length=255)),
                ('column_order', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('extracted', 'Extracted Data'), ('evaluation', 'Rule Engine'), ('scoring', 'Scoring Engine'), ('document', 'Document')], default='extracted', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_columns', to='documents.assessmentframework')),
            ],
            options={
                'ordering': ['column_order'],
            },
        ),
    ]
