# Generated by Django 6.0.6 on 2026-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_outputcolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputcolumn',
            name='source',
            field=models.CharField(choices=[('document', 'Document'), ('extracted', 'Extracted Data'), ('evaluation', 'Evaluation'), ('rule', 'Rule Engine'), ('scoring', 'Scoring Engine')], default='extracted', max_length=30),
        ),
    ]
