# Generated by Django 6.0.6 on 2026-07-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_outputcolumn_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkrule',
            name='match_value',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='FrameworkRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('eligible', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=10)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='documents.assessmentframework')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
