# Generated by Django 6.0.6 on 2026-07-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_frameworkrule_match_value_frameworkrulegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkrule',
            name='rule_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='documents.frameworkrulegroup'),
        ),
    ]
