# Generated by Django 6.0.6 on 2026-07-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_frameworkrule_rule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkrule',
            name='rule_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_rules', to='documents.frameworkrulegroup'),
        ),
    ]
